version: '2'
services:
  hello:
    container_name: hello
    build:
      #context: attin
      dockerfile: Dockerfile
    image: hello:1
    ports:
      - "8888:8888"
    expose:
      - "8888"
#    networks:
#      - spring-cloud-network
#networks:
#  spring-cloud-network:
#    driver: bridge